openapi: 3.0.0
info:
  title: V2.v1
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /v1/pepe:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-v1-pepe
      description: ''
components:
  schemas: {}
