openapi: 3.0.0
info:
  title: test
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /v2/pepe:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-v2-pepe
components:
  schemas: {}
